name: TicTacToe JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Compile Java files
        run: javac TicTacToe.java -d out/

      - name: Create JAR
        run: |
          cd out
          jar cf TicTacToe.jar *

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: TicTacToe-JAR
          path: out/TicTacToe.jar