name: Build TicTacToe JAR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build JAR
      run: javac TicTacToe.java && jar cfe TicTacToe.jar TicTacToe TicTacToe.class

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: tictactoe-jar
        path: TicTacToe.jar